import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { FC, PropsWithChildren, ReactNode } from 'react';

import { BasicLayout } from '@/landing-page/components/basic-layout';
import { HeadSection } from '@/landing-page/components/head-section';

import GLOBAL_SETTINGS from '@/configs/global';

import '@/styles/globals.scss';
import '@/styles/properties.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: GLOBAL_SETTINGS.DEFAULT_TITLE,
  description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren> = ({ children }): ReactNode => (
  <html lang='en'>
    <HeadSection />
    <body className={inter.className}>
      <BasicLayout>{children}</BasicLayout>
    </body>
  </html>
);

export default RootLayout;
