import { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Favicon from '/public/favicon.ico';

import '@/styles/globals.scss';
import '@/styles/properties.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Spotify',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang='en'>
    <body className={inter.className}>{children}</body>
  </html>
);

export default RootLayout;
